In [16]:
import pandas as pd 
import numpy as np 
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("US_Regional_Sales_Data.csv")
print(df.head()) 
print(df.dtypes)

df['Unit Price'] = df['Unit Price'].replace('[\$,]', '', regex=True).astype(float)
df['Unit Cost'] = df['Unit Cost'].replace('[\$,]', '', regex=True).astype(float)

# 4. VERIFICAMOS
print("\n--- DESPUÉS DE LA CONVERSIÓN ---")
print("Tipos de datos:")
print(df[['Unit Price', 'Unit Cost']].dtypes)
print("\nPrimeros valores de Unit Price (ahora números):")
print(df['Unit Price'].head())

print(f"Count: {df['Unit Price'].count()}") # muestra el conteo de valores no nulos en la columna "Amount"
print(f"Mean: {df['Unit Price'].mean():.2f}")

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [12]:
df.filter(items=['Unit Price', 'Unit Cost'],axis=1) # describe muestra estadísticas descriptivas de las columnas seleccionadas

      Unit Price  Unit Cost
0         1963.1    1001.18
1         3939.6    3348.66
2         1775.5     781.22
3         2324.9    1464.69
4         1822.4    1476.14
...          ...        ...
7986       234.5     121.94
7987      3202.6    1921.56
7988      3825.7    2792.76
7989      1072.0     804.00
7990      2211.0    1370.82

[7991 rows x 2 columns]

In [14]:
df[df["Unit Price"] < 2000].sort_values(by="Discount Applied", ascending=False)

NameError: name 'df' is not defined

In [ ]:
df.reset_index(inplace=True) #para regresear la forma anterior

In [28]:
df.sort_index()

,index,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Cost
Unit Price,,,,,,,,,,,,,,,,
167.5,5248,SO - 0005349,Online,WARE-XYS1001,23/8/19,14/2/20,9/3/2020,17/3/20,USD,15,32,57,9,5,0.05,134.00
167.5,1681,SO - 0001782,Online,WARE-NMK1003,27/10/18,17/12/18,3/1/2019,13/1/19,USD,20,45,194,32,4,0.05,125.63
167.5,6190,SO - 0006291,Online,WARE-PUJ1005,1/12/2019,02/06/2020,6/6/2020,7/6/2020,USD,15,20,322,12,4,0.10,130.65
167.5,5698,SO - 0005799,In-Store,WARE-UHY1004,1/12/2019,06/04/2020,12/4/2020,14/4/20,USD,12,39,244,27,8,0.05,132.33
167.5,6312,SO - 0006413,Online,WARE-XYS1001,10/3/2020,17/6/20,15/7/20,23/7/20,USD,14,28,31,35,4,0.40,98.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6559.3,3603,SO - 0003704,Online,WARE-UHY1004,4/2/2019,29/7/19,18/8/19,27/8/19,USD,15,9,252,10,6,0.30,3345.24
6559.3,3963,SO - 0004064,In-Store,WARE-XYS1001,15/5/19,12/09/2019,23/9/19,29/9/19,USD,11,16,22,29,5,0.05,4132.36
6559.3,4350,SO - 0004451,Wholesale,WARE-NMK1003,23/8/19,31/10/19,10/11/2019,17/11/19,USD,28,10,176,10,1,0.30,5444.22
6559.3,5265,SO - 0005366,Distributor,WARE-NMK1003,1/12/2019,16/2/20,26/2/20,28/2/20,USD,25,16,112,19,3,0.30,3279.65
6566.0,1776,SO - 0001877,Distributor,WARE-PUJ1005,27/10/18,26/12/18,3/1/2019,13/1/19,USD,23,17,328,11,3,0.15,4202.24

In [29]:
df.iloc[0:3, 0:2]

            index  OrderNumber
Unit Price
1963.1          0  SO - 000101
3939.6          1  SO - 000102
1775.5          2  SO - 000103

In [35]:
group_by_frame = df.groupby("WarehouseCode")

In [37]:
df.head()

,index,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Cost
Unit Price,,,,,,,,,,,,,,,,
1963.1,0,SO - 000101,In-Store,WARE-UHY1004,31/12/17,31/5/18,14/6/18,19/6/18,USD,6,15,259,12,5,0.08,1001.18
3939.6,1,SO - 000102,Online,WARE-NMK1003,31/12/17,31/5/18,22/6/18,2/7/2018,USD,14,20,196,27,3,0.08,3348.66
1775.5,2,SO - 000103,Distributor,WARE-UHY1004,31/12/17,31/5/18,21/6/18,1/7/2018,USD,21,16,213,16,1,0.05,781.22
2324.9,3,SO - 000104,Wholesale,WARE-NMK1003,31/12/17,31/5/18,2/6/2018,7/6/2018,USD,28,48,107,23,8,0.08,1464.69
1822.4,4,SO - 000105,Distributor,WARE-NMK1003,10/4/2018,31/5/18,16/6/18,26/6/18,USD,22,49,111,26,8,0.10,1476.14

In [38]:
df.reset_index()

,Unit Price,index,OrderNumber,Sales Channel,WarehouseCode,ProcuredDate,OrderDate,ShipDate,DeliveryDate,CurrencyCode,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Cost
0,1963.1,0,SO - 000101,In-Store,WARE-UHY1004,31/12/17,31/5/18,14/6/18,19/6/18,USD,6,15,259,12,5,0.08,1001.18
1,3939.6,1,SO - 000102,Online,WARE-NMK1003,31/12/17,31/5/18,22/6/18,2/7/2018,USD,14,20,196,27,3,0.08,3348.66
2,1775.5,2,SO - 000103,Distributor,WARE-UHY1004,31/12/17,31/5/18,21/6/18,1/7/2018,USD,21,16,213,16,1,0.05,781.22
3,2324.9,3,SO - 000104,Wholesale,WARE-NMK1003,31/12/17,31/5/18,2/6/2018,7/6/2018,USD,28,48,107,23,8,0.08,1464.69
4,1822.4,4,SO - 000105,Distributor,WARE-NMK1003,10/4/2018,31/5/18,16/6/18,26/6/18,USD,22,49,111,26,8,0.10,1476.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7986,234.5,7986,SO - 0008087,In-Store,WARE-MKL1006,26/9/20,30/12/20,7/1/2021,14/1/21,USD,9,41,339,29,1,0.08,121.94
7987,3202.6,7987,SO - 0008088,Online,WARE-NMK1003,26/9/20,30/12/20,2/1/2021,4/1/2021,USD,14,29,202,3,6,0.05,1921.56
7988,3825.7,7988,SO - 0008089,Online,WARE-UHY1004,26/9/20,30/12/20,23/1/21,26/1/21,USD,14,32,241,35,5,0.20,2792.76
7989,1072.0,7989,SO - 0008090,Online,WARE-NMK1003,26/9/20,30/12/20,20/1/21,25/1/21,USD,20,42,112,36,8,0.10,804.00
7990,2211.0,7990,SO - 0008091,In-Store,WARE-UHY1004,26/9/20,30/12/20,13/1/21,19/1/21,USD,6,41,237,43,5,0.08,1370.82

In [45]:
df.groupby("Sales Channel").mean(numeric_only=True)

,index,_SalesTeamID,_CustomerID,_StoreID,_ProductID,Order Quantity,Discount Applied,Unit Cost
Sales Channel,,,,,,,,
Distributor,4014.833455,22.698182,25.290909,186.717091,24.167273,4.572364,0.114196,1456.117055
In-Store,3966.953608,6.302001,25.402668,185.039418,23.779563,4.511219,0.115088,1424.761516
Online,4011.281649,16.099381,25.671340,181.110103,23.548041,4.493608,0.117682,1434.802256
Wholesale,4023.827548,26.774916,25.331467,182.483763,23.741321,4.591265,0.114434,1413.197088

df.groupby("columna").min(), el índice original (0-10) desaparece y es reemplazado por los valores únicos de la columna que usaste en el groupby

In [ ]:
df['Order Quantity'].head()

NameError: name 'df' is not defined